services:
  # Servicio de MongoDB
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - access_path_network

  # Servicio de tu aplicación Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: access_path_server
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_URI=${DB_URI}
      - PORT=${PORT}
    depends_on:
      - mongodb
    networks:
      - access_path_network
      - proxy
    volumes:
      - ./logs:/app/logs  # Para logs si los necesitas
    shm_size: '1g'

  # MongoDB Express (interfaz web opcional para administrar MongoDB)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - access_path_network
      - proxy

volumes:
  mongodb_data:
    driver: local

networks:
  access_path_network:
    driver: bridge
  proxy:
    external: true